[project]
name = "deliveryeta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jerymy-k", email = "karimimoha0@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "joblib>=1.6.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
]

[project.scripts]
deliveryeta = "deliveryeta:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
